#Database Connection
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blogger-db
    username: derrickmadumere
    password: madumere
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false
        use_sql_comments: true
    hibernate:
      ddl-auto: update
  threads:
    virtual:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: derrick.onyekachi@gmail.com
    password: ialsrfvpjfeomtqo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /api/v1
  error:
    include-stacktrace: on_param
logging:
  level:
    org.springframework.security: DEBUG
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
